### ISSUE TITLE
Error: No targets given and there is no package in the current directory

### ISSUE THREAD

**Issue by newhoggy** [kowainik/policeman#52]
```
$ git clone git@github.com:haskell-works/hw-bits.git
$ cd hw-bits
$ policeman
⚙  curl --silent 'http://hackage.haskell.org/package/hw-bits/hw-bits-0.7.1.0.tar.gz' --output .policeman-evidence/hw-bits-0.7.1.0.tar.gz
⚙  tar -xf .policeman-evidence/hw-bits-0.7.1.0.tar.gz -C .policeman-evidence
⚙  cabal clean
⚙  cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0'
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

policeman: callCommand: cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0' (exit 1): failed
```

**Comment by lukel97** [comment]
I think this happens when there's a `cabal.project` file in the source repo's directory, since the clone inside `.policeman-evidence` will then pick up the `cabal.project` file in the root and complain that the clone isn't listed in the packages field. Maybe it could be cloned into `$TMPDIR` instead to avoid this?

**Comment by newhoggy** [comment]
Can confirm that was my problem.

It would be nice if this were to work in those cases because I sometimes commit my `cabal.project` file and would like to run this in CI.

**Comment by chshersh** [comment]
@bubba thanks for identifying the root of the issue 👍 We've discussed the problem with @vrom911, and we were trying to tell `cabal` explicitly what to build by passing `lib:hw-bits` argument but this doesn't solve the problem completely.

@newhoggy commiting the `cabal.project` file is totally fine, and `policeman` should be able to work correctly in a presence of `cabal.project`. I just haven't expected this behavior from `cabal-install`. Using a temporary directory sounds like a reasonable solution.

**Comment by 23Skidoo** [comment]
I think that an easy workaround would be for `policeman` to put a dummy `cabal.project` file to `.policeman-evidence/hw-bits-0.7.1.0` dir with the following contents:

```
packages: .
```
