### ISSUE TITLE
ghc-8.10.1 support?

### ISSUE THREAD

**Issue by peti** [kowainik/policeman#57]
Will there be an update that supports the most recent 8.10.1 version of GHC?

**Comment by chshersh** [comment]
@peti `policeman` depends on other libraries, including `ghc` package, so it may take some time to update to GHC-8.10. But we have it in plans for the nearest future.

**Comment by peti** [comment]
I have successfully built policeman with ghc-8.10.1 (and used the
generated binary, too) just by specifying "--allow-newer" to the Cabal
build, so I don't think that there's much to updating beyond relaxing
the appropriate version constraints.

**Comment by chshersh** [comment]
@peti That's very interesting since GHC-8.10 changed its API a lot. If you want to give it a try, you can upgrade bounds in the `policeman` directly and send a PR, if you feel like it.

**Comment by peti** [comment]
I don't think a PR is the way to go. Why don't just update the constraints on Hackage?

https://packdeps.haskellers.com/feed?needle=policeman

**Comment by vrom911** [comment]
I think PR is the only way to go. Without that, it is not possible to update only the Hackage constraints. We are testing the package with the different GHC versions and want to make sure that it works properly.

**Comment by peti** [comment]
Well, whoever feels strongly about the need for a PR should create one. I'm not gonna.

**Comment by hasufell** [comment]
> Why don't just update the constraints on Hackage?

Because hackage does not commit back to git repos.
