### ISSUE TITLE
Policeman doesn't work in the HLS codebase

### ISSUE THREAD

**Issue by pepeiborra** [kowainik/policeman#67]
We want to use policeman to drive [HLS](http://github.com/haskell/haskell-language-server) version bumps. 
I get this error when I run policeman inside the `ghcide` folder:

```
[nix-shell:~/scratch/ide/ghcide]$ policeman 
⚙  curl --silent 'http://hackage.haskell.org/package/ghcide/ghcide-1.5.0.tar.gz' --output .policeman-evidence/ghcide-1.5.0.tar.gz
⚙  tar -xf .policeman-evidence/ghcide-1.5.0.tar.gz -C .policeman-evidence
⚙  cabal clean
⚙  cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0'
cabal: No targets given and there is no package in the current directory. Use
the target 'all' for all packages in the project or specify packages or
components by name or location. See 'cabal build --help' for more details on
target options.

policeman: callCommand: cabal v2-build '--ghc-options=-fwrite-ide-info' '--ghc-options=-hiedir=.hie' '--verbose=0' (exit 1): failed
```

Am I doing something wrong? Note that HLS is a multi-component Cabal project. The error above is for the `ghcide` package, but I get the same error for other HLS Cabal packages too. 

Versions:
```

[nix-shell:~/scratch/ide/ghcide]$ policeman --version
👮 Policeman v0.0.0.0
 ➤ Git revision: UNKNOWN
 ➤ Commit date:  UNKNOWN

[nix-shell:~/scratch/ide/ghcide]$ ghc-pkg list policeman
/nix/store/izbbvg2igyl8vm8cmbmgicp390kq85gr-ghc-8.10.4-with-packages/lib/ghc-8.10.4/package.conf.d
    policeman-0.0.0.0

[nix-shell:~/scratch/ide/ghcide]$ cabal --version
cabal-install version 3.6.2.0
compiled using version 3.6.2.0 of the Cabal library 
```

**Comment by chshersh** [comment]
@pepeiborra I believe this is a duplicate of the following issue:

* https://github.com/kowainik/policeman/issues/52

If you install `policeman` from the latest commit in the `main` branch it should work. Here is relevant code:

https://github.com/kowainik/policeman/blob/26a92678c76b145ad9ae30054bf978a0d6ec2a58/src/Policeman/Hie.hs#L20-L37

**Comment by pepeiborra** [comment]
Awesome! I will close this issue then. 
Do you plan to make a Hackage release any time soon?
